In [2]:

# ANÁLISIS EXPLORATORIO DE DATOS (EDA)
# IMPORTACIÓN DE LIBRERÍAS

# Pandas: trabajar con tablas y datos.
import pandas as pd

# NumPy: operaciones matemáticas y estadísticas.
import numpy as np

# Matplotlib: creación de gráficos.
import matplotlib.pyplot as plt

# Seaborn: gráficos estadísticos.
import seaborn as sns

# Permite seleccionar archivos desde Google Colab.
from google.colab import files

# Permite trabajar con texto y eliminar tildes.
import unicodedata

# CONFIGURACIÓN D GRAFICOS

# Configuramos el estilo de los gráficos.
sns.set_style("whitegrid")

# Permitimos visualizar todas las columnas de los DataFrames.
pd.set_option("display.max_columns", None)

# FUNCIÓN PARA VERIFICAR QUE EL DATASET ESTÉ CARGADO
def dataset_cargado():

    """
    Verifica si el dataset fue cargado.

    Devuelve:
    True  -> si existe df_original.
    False -> si todavía no se ha cargado.
    """

    return 'df_original' in globals()

# FUNCIÓN PARA VERIFICAR QUE LA TABLA MODIFICADA EXISTA
def tabla_limpia():

    """
    Verifica si ya se realizó la preparación de los datos.

    Devuelve:
    True  -> si existe df_modificada.
    False -> si todavía no existe.
    """

    return 'df_modificada' in globals()

# MENÚ PRINCIPAL

while True:

    print("\n================================================")
    print("              MENÚ PRINCIPAL")
    print("================================================")

    print("1. Cargar archivo CSV")
    print("2. Introducir nuevos datos")
    print("3. Mostrar información del conjunto de datos")
    print("4. Analizar tipos de datos")
    print("5. Analizar y tratar valores nulos")
    print("6. Analizar y tratar datos duplicados")
    print("7. Obtener estadísticas descriptivas")
    print("8. Filtrar o consultar datos")
    print("9. Realizar agrupaciones y operaciones")
    print("10. Generar representaciones gráficas")
    print("11. Realizar análisis adicional")
    print("12. Salir")

    opcion = input("\nSeleccione una opción: ").strip()



    # OPCIÓN 1. CARGAR ARCHIVO CSV

    if opcion == "1":


        print("========CARGAR ARCHIVO CSV==========")

        try:

            # Abrimos el selector de archivos de Google Colab.
            archivo = files.upload()

            # Verificamos que se haya seleccionado algún archivo.
            if not archivo:

                print("\nNo se seleccionó ningún archivo.")

                continue

            # Obtenemos el nombre del archivo seleccionado.
            nombre = next(iter(archivo))

            # Leemos el archivo CSV con pandas.
            df_original = pd.read_csv(nombre)

            # Creamos una copia para trabajar.
            df = df_original.copy()

            # Reiniciamos la tabla modificada.
            if 'df_modificada' in globals():
                del df_modificada

            print("\nArchivo cargado correctamente.")

            print("\nNombre del archivo:")
            print(nombre)

            print("\nCantidad de filas y columnas:")
            print(df.shape)

            print("\nPrimeras 10 filas del archivo:")

            display(df.head(10))

            print(
                "\nAhora puedes utilizar la opción 2 "
                "para introducir nuevos registros."
            )

        except Exception as e:

            print("\nNo fue posible cargar el archivo.")
            print("Error:", e)


    # OPCIÓN 2. INTRODUCIR NUEVOS DATOS

    elif opcion == "2":


        print("==========INTRODUCIR NUEVOS DATOS==========")


        # Primero debemos tener cargado el CSV.
        if not dataset_cargado():

            print(
                "\nPrimero debes cargar el archivo CSV "
                "utilizando la opción 1."
            )

            continue


        print(
            "\nEsta opción permite agregar nuevos registros "
            "al dataset cargado."
        )

        print(
            "\nDeja el campo vacío si deseas registrar "
            "un valor nulo."
        )


        while True:

            nuevo_registro = {}



            # ID DE VENTA

            valor = input("\nID de venta: ").strip()

            if valor == "":
                nuevo_registro["id_venta"] = np.nan

            else:

                try:
                    nuevo_registro["id_venta"] = int(valor)

                except ValueError:

                    print(
                        "El ID de venta debe ser un número entero."
                    )

                    continue



            # FECHA

            nuevo_registro["fecha"] = input(
                "Fecha (ejemplo: 2025-01-15): "
            ).strip()

            # Si se deja vacío, se registra como nulo.
            if nuevo_registro["fecha"] == "":
                nuevo_registro["fecha"] = np.nan



            # PRODUCTO

            nuevo_registro["producto"] = input(
                "Producto: "
            ).strip()

            if nuevo_registro["producto"] == "":
                nuevo_registro["producto"] = np.nan


            # CATEGORÍA

            nuevo_registro["categoria"] = input(
                "Categoría: "
            ).strip()

            if nuevo_registro["categoria"] == "":
                nuevo_registro["categoria"] = np.nan


            # CANTIDAD

            valor = input(
                "Cantidad: "
            ).strip()

            if valor == "":
                nuevo_registro["cantidad"] = np.nan

            else:

                try:
                    nuevo_registro["cantidad"] = int(valor)

                except ValueError:

                    print(
                        "La cantidad debe ser un número entero."
                    )

                    continue


           # PRECIO UNITARIO

            valor = input(
                "Precio unitario: "
            ).strip()

            if valor == "":
                nuevo_registro["precio_unitario"] = np.nan

            else:

                try:
                    nuevo_registro["precio_unitario"] = float(
                        valor
                    )

                except ValueError:

                    print(
                        "El precio debe ser un número."
                    )

                    continue


            # VENDEDOR

            nuevo_registro["vendedor"] = input(
                "Vendedor: "
            ).strip()

            if nuevo_registro["vendedor"] == "":
                nuevo_registro["vendedor"] = np.nan


            # REGIÓN

            nuevo_registro["region"] = input(
                "Región: "
            ).strip()

            if nuevo_registro["region"] == "":
                nuevo_registro["region"] = np.nan


            # MÉTODO DE PAGO

            nuevo_registro["metodo_pago"] = input(
                "Método de pago: "
            ).strip()

            if nuevo_registro["metodo_pago"] == "":
                nuevo_registro["metodo_pago"] = np.nan


            # CLIENTE FRECUENTE

            nuevo_registro["cliente_frecuente"] = input(
                "¿Cliente frecuente? (Sí/No): "
            ).strip()

            if nuevo_registro["cliente_frecuente"] == "":
                nuevo_registro["cliente_frecuente"] = np.nan


            # CREAR DATAFRAME CON EL NUEVO REGISTRO

            nuevo_df = pd.DataFrame(
                [nuevo_registro]
            )


            # AGREGAR EL NUEVO REGISTRO

            df_original = pd.concat(
                [
                    df_original,
                    nuevo_df
                ],
                ignore_index=True
            )


            # Actualizamos también la copia de trabajo.
            df = df_original.copy()


            print(
                "\nRegistro agregado correctamente."
            )

            print(
                "\nCantidad actual de registros:",
                len(df_original)
            )


            # Mostrar el registro recién agregado.
            print("\nRegistro agregado:")

            display(
                nuevo_df
            )

            # Preguntar si desea introducir otro registro.
            continuar = input(
                "\n¿Desea introducir otro registro? (s/n): "
            ).strip().lower()


            if continuar != "s":

                print(
                    "\nRegresando al menú principal..."
                )

                break



    # OPCIÓN 3. INFORMACIÓN DEL DATASET

    elif opcion == "3":

        print("\n================================================")
        print("       INFORMACIÓN DEL CONJUNTO DE DATOS")
        print("================================================")


        if not dataset_cargado():

            print(
                "\nPrimero debes cargar el archivo CSV "
                "en la opción 1."
            )

            continue


        # Cantidad de filas.
        print(
            "\nCantidad de filas:",
            df_original.shape[0]
        )


        # Cantidad de columnas.
        print(
            "Cantidad de columnas:",
            df_original.shape[1]
        )


        # Nombres de columnas.
        print("\nColumnas del dataset:")

        print(
            df_original.columns.tolist()
        )


        # Información general.
        print(
            "\nInformación de los tipos de datos:"
        )

        df_original.info()


        # Primeras filas.
        print(
            "\nPrimeras 10 filas:"
        )

        display(
            df_original.head(10)
        )



    # OPCIÓN 4. ANÁLISIS DE TIPOS DE DATOS

    elif opcion == "4":


        print("=============ÁLISIS DE TIPOS DE DATOS=============")

        if not dataset_cargado():

            print(
                "\nPrimero debes cargar el archivo CSV."
            )

            continue



        # TABLA ORIGINAL

        tabla_tipos = pd.DataFrame({

            "Nombre de columna":
                df_original.columns,

            "Tipo de dato":
                df_original.dtypes.astype(str),

            "Ejemplo": [

                df_original[col].iloc[0]
                if len(df_original) > 0
                else np.nan

                for col in df_original.columns

            ]

        })


        print("\nTABLA ORIGINAL:")

        display(
            tabla_tipos
        )


        # CREAR COPIA PARA MODIFICAR

        df_modificada = df_original.copy()


        # CONVERTIR FECHA

        if "fecha" in df_modificada.columns:

            df_modificada["fecha"] = pd.to_datetime(
                df_modificada["fecha"],
                errors="coerce"
            )


        # CONVERTIR ID_VENTA

        if "id_venta" in df_modificada.columns:

            df_modificada["id_venta"] = pd.to_numeric(
                df_modificada["id_venta"],
                errors="coerce"
            ).astype("Int64")


        # CONVERTIR CANTIDAD

        if "cantidad" in df_modificada.columns:

            df_modificada["cantidad"] = pd.to_numeric(
                df_modificada["cantidad"],
                errors="coerce"
            ).astype("Int64")


        # CONVERTIR PRECIO UNITARIO

        if "precio_unitario" in df_modificada.columns:

            df_modificada["precio_unitario"] = pd.to_numeric(
                df_modificada["precio_unitario"],
                errors="coerce"
            )


        # TABLA MODIFICADA

        tabla_modificada = pd.DataFrame({

            "Nombre de columna":
                df_modificada.columns,

            "Tipo de dato":
                df_modificada.dtypes.astype(str),

            "Ejemplo": [

                df_modificada[col].iloc[0]
                if len(df_modificada) > 0
                else np.nan

                for col in df_modificada.columns

            ]

        })


        print("\nTABLA MODIFICADA:")

        display(
            tabla_modificada
        )


        print(
            "\nLos tipos de datos fueron preparados "
            "correctamente."
        )


    # OPCIÓN 5. ANALIZAR Y TRATAR VALORES NULOS

    elif opcion == "5":


        print("============ANALIZAR Y TRATAR VALORES NULOS============")


        if not tabla_limpia():

            print(
                "\nPrimero debes ejecutar la opción 4."
            )

            continue


        # ELIMINAR FILAS COMPLETAMENTE VACÍAS

        filas_vacias = (
            df_modificada
            .isnull()
            .all(axis=1)
        )


        print(
            "\nFilas completamente vacías:",
            filas_vacias.sum()
        )


        if filas_vacias.sum() > 0:

            df_modificada = (
                df_modificada[
                    ~filas_vacias
                ]
                .reset_index(drop=True)
            )


            print(
                "Las filas completamente vacías "
                "fueron eliminadas."
            )


        # MOSTRAR CANTIDAD DE NULOS

        print(
            "\nCANTIDAD DE VALORES NULOS POR COLUMNA:"
        )

        print(
            df_modificada.isnull().sum()
        )


        # MOSTRAR FILAS CON NULOS

        filas_con_nulos = df_modificada[
            df_modificada.isnull().any(axis=1)
        ]


        print(
            "\nCantidad de filas que contienen "
            "al menos un valor nulo:",
            len(filas_con_nulos)
        )


        print(
            "\nREGISTROS CON VALORES NULOS:"
        )

        display(
            filas_con_nulos
        )


       # REEMPLAZAR NULOS DE VARIABLES CATEGÓRICAS

        columnas_texto = [

            "categoria",
            "producto",
            "vendedor",
            "metodo_pago"

        ]


        for columna in columnas_texto:

            if columna in df_modificada.columns:

                df_modificada[columna] = (
                    df_modificada[columna]
                    .fillna("Desconocido")
                )


        # REEMPLAZAR NULOS DE REGIÓN

        if "region" in df_modificada.columns:

            df_modificada["region"] = (
                df_modificada["region"]
                .fillna("Desconocida")
            )


        # ANALIZAR FECHAS NULAS

        if "fecha" in df_modificada.columns:

            registros_fecha_nula = (
                df_modificada[
                    df_modificada["fecha"].isnull()
                ]
            )


            print(
                "\nREGISTROS CON FECHA NULA:"
            )

            print(
                "Cantidad:",
                len(registros_fecha_nula)
            )

            display(
                registros_fecha_nula
            )


            # Las fechas nulas se mantienen como NaT
            # porque no es correcto inventar una fecha.



        # ANALIZAR PRECIO UNITARIO NULO

        if "precio_unitario" in df_modificada.columns:

            registros_precio_nulo = (
                df_modificada[
                    df_modificada["precio_unitario"].isnull()
                ]
            )


            print(
                "\nREGISTROS CON PRECIO_UNITARIO NULO:"
            )

            print(
                "Cantidad:",
                len(registros_precio_nulo)
            )

            display(
                registros_precio_nulo
            )


            # MEDIANA DEL PRECIO POR PRODUCTO

            mediana_por_producto = (
                df_modificada
                .groupby("producto")["precio_unitario"]
                .median()
            )


            print(
                "\nMEDIANA DEL PRECIO UNITARIO POR PRODUCTO:"
            )

            display(
                mediana_por_producto
            )


            # Reemplazamos los precios nulos utilizando
            # la mediana correspondiente al producto.
            df_modificada["precio_unitario"] = (
                df_modificada["precio_unitario"]
                .fillna(
                    df_modificada["producto"]
                    .map(mediana_por_producto)
                )
            )



        # ANALIZAR CANTIDAD NULA

        if "cantidad" in df_modificada.columns:

            cantidad_nula = (
                df_modificada["cantidad"].isnull()
            )


            print(
                "\nREGISTROS CON CANTIDAD NULA:"
            )

            print(
                "Cantidad:",
                cantidad_nula.sum()
            )


            if cantidad_nula.sum() > 0:

                display(
                    df_modificada[cantidad_nula]
                )


                # No inventamos automáticamente una cantidad.
                # Se mantiene nula para evitar alterar
                # artificialmente las ventas.



        # ANALIZAR ID_VENTA NULO

        if "id_venta" in df_modificada.columns:

            id_nulo = (
                df_modificada["id_venta"].isnull()
            )


            print(
                "\nREGISTROS CON ID_VENTA NULO:"
            )

            print(
                "Cantidad:",
                id_nulo.sum()
            )


            if id_nulo.sum() > 0:

                display(
                    df_modificada[id_nulo]
                )


        # COMPROBACIÓN FINAL DE NULOS


        print(
            "===========ULOS DESPUÉS DEL TRATAMIENTO==========="
        )


        print(
            df_modificada.isnull().sum()
        )



        # CONTAR DESCONOCIDOS

        print(
            "\nCANTIDAD DE 'DESCONOCIDO' POR COLUMNA:"
        )


        columnas_desconocido = [

            "categoria",
            "producto",
            "vendedor",
            "metodo_pago"

        ]


        columnas_existentes = [

            col
            for col in columnas_desconocido
            if col in df_modificada.columns

        ]


        if columnas_existentes:

            cantidad_desconocidos = (
                df_modificada[
                    columnas_existentes
                ]
                .eq("Desconocido")
                .sum()
            )

            print(
                cantidad_desconocidos
            )


        print(
            "\nTratamiento de valores nulos terminado."
        )


       # OPCIÓN 6. ANALIZAR Y TRATAR DUPLICADOS

    elif opcion == "6":


        print(
            "==========ANALIZAR Y TRATAR DUPLICADOS=========="
        )


        if not tabla_limpia():

            print(
                "\nPrimero debes ejecutar las opciones 4 y 5."
            )

            continue


        # DUPLICADOS COMPLETOS

        duplicados = df_modificada[
            df_modificada.duplicated(
                keep=False
            )
        ]

        print(
            "\nREGISTROS COMPLETAMENTE DUPLICADOS:"
        )

        print(
            "Cantidad:",
            len(duplicados)
        )


        if len(duplicados) > 0:

            display(
                duplicados
            )


            eliminar = input(
                "\n¿Desea eliminar los duplicados completos? "
                "(s/n): "
            ).strip().lower()


            if eliminar == "s":

                df_modificada = (
                    df_modificada
                    .drop_duplicates()
                    .reset_index(drop=True)
                )


                print(
                    "\nDuplicados completos eliminados."
                )


        else:

            print(
                "No se encontraron registros "
                "completamente duplicados."
            )


        # ID DE VENTA REPETIDOS

        print(
            "\n================================================"
        )

        print(
            "             ID_VENTA REPETIDOS"
        )

        print(
            "================================================"
        )


        conteo_id = (
            df_modificada["id_venta"]
            .value_counts()
        )


        ids_repetidos = conteo_id[
            conteo_id > 1
        ]


        print(
            "Cantidad de ID repetidos:",
            len(ids_repetidos)
        )


        if len(ids_repetidos) > 0:

            print(
                "\nID de venta repetidos:"
            )

            print(
                ids_repetidos
            )


            print(
                "\nREGISTROS CORRESPONDIENTES:"
            )


            registros_id_repetidos = (
                df_modificada[
                    df_modificada["id_venta"]
                    .isin(ids_repetidos.index)
                ]
                .sort_values("id_venta")
            )


            display(
                registros_id_repetidos
            )


            print(
                "\nEstos registros deben revisarse "
                "antes de eliminar alguno."
            )


        else:

            print(
                "\nNo se encontraron ID de venta repetidos."
            )


        # ESTANDARIZAR VENDEDORES

        print(
            "\n================================================"
        )

        print(
            "          ESTANDARIZACIÓN DE VENDEDORES"
        )

        print(
            "================================================"
        )


        print(
            "\nVendedores antes de estandarizar:"
        )

        print(
            df_modificada["vendedor"].value_counts()
        )


        # Eliminamos espacios innecesarios y estandarizamos
        # mayúsculas y minúsculas.
        df_modificada["vendedor"] = (
            df_modificada["vendedor"]
            .astype(str)
            .str.strip()
            .str.title()
        )


        print(
            "\nVendedores después de estandarizar:"
        )

        print(
            df_modificada["vendedor"].value_counts()
        )


        print(
            "\nVendedores únicos:"
        )

        print(
            df_modificada["vendedor"].unique()
        )


        print(
            "\nCantidad de vendedores únicos:",
            df_modificada["vendedor"].nunique()
        )


        print(
            "\nAnálisis de duplicados terminado."
        )


    # OPCIÓN 7. ESTADÍSTICAS DESCRIPTIVAS

    elif opcion == "7":



        print(
            "===========ESTADÍSTICAS DESCRIPTIVAS==========="
        )



        if not tabla_limpia():

            print(
                "\nPrimero debes ejecutar las opciones 4, 5 y 6."
            )

            continue


        # Variables numéricas del dataset.
        columnas_numericas = [

            "cantidad",
            "precio_unitario"

        ]


       # TABLA RESUMEN

        print(
            "\n===== RESUMEN ESTADÍSTICO ====="
        )


        estadisticas = (
            df_modificada[
                columnas_numericas
            ]
            .describe()
            .T
        )


        display(
            estadisticas
        )


       # MEDIDAS INDIVIDUALES


        for columna in columnas_numericas:

            valores = (
                df_modificada[columna]
                .dropna()
            )


            print(
                f"\n===== {columna.upper()} ====="
            )


            print(
                "Cantidad de valores:",
                valores.count()
            )


            print(
                "Promedio:",
                valores.mean()
            )


            print(
                "Desviación estándar:",
                valores.std()
            )


            print(
                "Mínimo:",
                valores.min()
            )


            print(
                "Q1:",
                valores.quantile(0.25)
            )


            print(
                "Mediana:",
                valores.median()
            )


            print(
                "Q3:",
                valores.quantile(0.75)
            )


            print(
                "Máximo:",
                valores.max()
            )



        # VALORES ATÍPICOS DE PRECIO UNITARIO

        print(
            "\n================================================"
        )

        print(
            "       VALORES ATÍPICOS DE PRECIO_UNITARIO"
        )

        print(
            "================================================"
        )


        precios = (
            df_modificada["precio_unitario"]
            .dropna()
        )


        Q1 = precios.quantile(0.25)

        Q3 = precios.quantile(0.75)

        RIC = Q3 - Q1

        limite_inferior = (
            Q1 - 1.5 * RIC
        )

        limite_superior = (
            Q3 + 1.5 * RIC
        )


        print(
            f"Q1: ₡{Q1:,.2f}"
        )

        print(
            f"Q3: ₡{Q3:,.2f}"
        )

        print(
            f"RIC: ₡{RIC:,.2f}"
        )

        print(
            f"Límite inferior: ₡{limite_inferior:,.2f}"
        )

        print(
            f"Límite superior: ₡{limite_superior:,.2f}"
        )


        atipicos_precio = df_modificada[
            (
                df_modificada["precio_unitario"]
                < limite_inferior
            )
            |
            (
                df_modificada["precio_unitario"]
                > limite_superior
            )
        ]


        print(
            "\nCantidad de valores atípicos:",
            len(atipicos_precio)
        )


        if len(atipicos_precio) > 0:

            display(
                atipicos_precio
            )

        else:

            print(
                "No se encontraron valores atípicos."
            )



        # PRECIO POR PRODUCTO

        print(
            "\n===== PRECIO UNITARIO POR PRODUCTO ====="
        )


        resumen_productos = (
            df_modificada
            .groupby("producto")["precio_unitario"]
            .agg(
                [
                    "count",
                    "min",
                    "mean",
                    "median",
                    "max"
                ]
            )
        )


        display(
            resumen_productos
        )


       # CANTIDADES NEGATIVAS

        print(
            "\n===== CANTIDADES NEGATIVAS ====="
        )


        cantidad_negativa = df_modificada[
            df_modificada["cantidad"] < 0
        ]


        print(
            "Cantidad de registros negativos:",
            len(cantidad_negativa)
        )


        if len(cantidad_negativa) > 0:

            display(
                cantidad_negativa
            )

        else:

            print(
                "No se encontraron cantidades negativas."
            )



    # OPCIÓN 8. FILTRAR Y CONSULTAR

    elif opcion == "8":


        print(
            "=========FILTRAR Y CONSULTAR DATOS========="
        )


        if not tabla_limpia():

            print(
                "\nPrimero debes ejecutar las opciones 4, 5 y 6."
            )

            continue


        while True:

            print("""
===== MENÚ DE CONSULTAS =====

1. Buscar por producto
2. Filtrar por categoría
3. Filtrar por vendedor
4. Filtrar por región
5. Filtrar por rango de precio
6. Filtrar por cantidad
7. Consultar por ID de venta
0. Regresar
""")


            consulta = input(
                "Seleccione una opción: "
            ).strip()



            # PRODUCTO

            if conulta == "1":

                producto = input(
                    "\nIngrese el nombre o parte del producto: "
                ).strip()


                resultado = df_modificada[
                    df_modificada["producto"]
                    .astype(str)
                    .str.contains(
                        producto,
                        case=False,
                        na=False
                    )
                ]


                if len(resultado) > 0:

                    display(resultado)

                    print(
                        "\nCantidad de registros:",
                        len(resultado)
                    )

                else:

                    print(
                        "\nNo se encontraron registros."
                    )


            # CATEGORÍA

            elif consulta == "2":

                categoria = input(
                    "\nIngrese la categoría: "
                ).strip()


                resultado = df_modificada[
                    df_modificada["categoria"]
                    .astype(str)
                    .str.contains(
                        categoria,
                        case=False,
                        na=False
                    )
                ]


                if len(resultado) > 0:

                    display(resultado)

                else:

                    print(
                        "\nNo se encontraron registros."
                    )



            # VENDEDOR

            elif consulta == "3":

                vendedor = input(
                    "\nIngrese el vendedor: "
                ).strip()


                resultado = df_modificada[
                    df_modificada["vendedor"]
                    .astype(str)
                    .str.contains(
                        vendedor,
                        case=False,
                        na=False
                    )
                ]


                if len(resultado) > 0:

                    display(resultado)

                else:

                    print(
                        "\nNo se encontraron registros."
                    )



            # REGIÓN

            elif consulta == "4":

                region = input(
                    "\nIngrese la región: "
                ).strip()


                resultado = df_modificada[
                    df_modificada["region"]
                    .astype(str)
                    .str.contains(
                        region,
                        case=False,
                        na=False
                    )
                ]


                if len(resultado) > 0:

                    display(resultado)

                else:

                    print(
                        "\nNo se encontraron registros."
                    )



            # RANGO DE PRECIO

            elif consulta == "5":

                try:

                    precio_min = float(
                        input(
                            "\nPrecio mínimo: "
                        )
                    )

                    precio_max = float(
                        input(
                            "Precio máximo: "
                        )
                    )


                    resultado = df_modificada[
                        (
                            df_modificada["precio_unitario"]
                            >= precio_min
                        )
                        &
                        (
                            df_modificada["precio_unitario"]
                            <= precio_max
                        )
                    ]


                    if len(resultado) > 0:

                        display(resultado)

                    else:

                        print(
                            "\nNo se encontraron registros."
                        )


                except ValueError:

                    print(
                        "\nDebe ingresar valores numéricos."
                    )



            # CANTIDAD

            elif consulta == "6":

                try:

                    cantidad = int(
                        input(
                            "\nIngrese la cantidad: "
                        )
                    )


                    resultado = df_modificada[
                        df_modificada["cantidad"]
                        == cantidad
                    ]


                    if len(resultado) > 0:

                        display(resultado)

                    else:

                        print(
                            "\nNo se encontraron registros."
                        )


                except ValueError:

                    print(
                        "\nDebe ingresar un número entero."
                    )


            # ID DE VENTA

            elif consulta == "7":

                try:

                    id_buscar = int(
                        input(
                            "\nIngrese el ID de venta: "
                        )
                    )


                    resultado = df_modificada[
                        df_modificada["id_venta"]
                        == id_buscar
                    ]


                    if len(resultado) > 0:

                        display(resultado)

                    else:

                        print(
                            "\nNo se encontró ese ID."
                        )


                except ValueError:

                    print(
                        "\nDebe ingresar un número entero."
                    )


            # REGRESAR

            elif consulta == "0":

                break


            else:

                print(
                    "\nOpción no válida."
                )



    # OPCIÓN 9. AGRUPACIONES Y OPERACIONES

    elif opcion == "9":


        print(
            "==========AGRUPACIONES Y OPERACIONE==========S"
        )


        if not tabla_limpia():

            print(
                "\nPrimero debes ejecutar las opciones 4, 5 y 6."
            )

            continue


        df_agrupada = df_modificada.copy()


        # Calculamos el total de cada venta.
        df_agrupada["total_venta"] = (
            df_agrupada["cantidad"]
            *
            df_agrupada["precio_unitario"]
        )


        while True:

            print("""
===== MENÚ DE AGRUPACIONES =====

1. Total vendido
2. Total vendido por producto
3. Total vendido por categoría
4. Total vendido por vendedor
5. Total vendido por región
6. Total vendido por método de pago
7. Cantidad total vendida por producto
8. Precio promedio por producto
9. Cantidad de ventas por producto
10. Ordenar productos por total vendido
11. Ordenar productos por precio promedio
12. Ordenar productos por cantidad vendida
0. Regresar
""")


            consulta = input(
                "Seleccione una opción: "
            ).strip()


            if consulta == "1":

                total = (
                    df_agrupada["total_venta"]
                    .sum()
                )

                print(
                    f"\nTotal vendido: ₡{total:,.2f}"
                )


            elif consulta == "2":

                resultado = (
                    df_agrupada
                    .groupby("producto")["total_venta"]
                    .sum()
                    .sort_values(
                        ascending=False
                    )
                )

                display(
                    resultado.to_frame(
                        "Total vendido"
                    )
                )


            elif consulta == "3":

                resultado = (
                    df_agrupada
                    .groupby("categoria")["total_venta"]
                    .sum()
                    .sort_values(
                        ascending=False
                    )
                )

                display(
                    resultado.to_frame(
                        "Total vendido"
                    )
                )


            elif consulta == "4":

                resultado = (
                    df_agrupada
                    .groupby("vendedor")["total_venta"]
                    .sum()
                    .sort_values(
                        ascending=False
                    )
                )

                display(
                    resultado.to_frame(
                        "Total vendido"
                    )
                )


            elif consulta == "5":

                resultado = (
                    df_agrupada
                    .groupby("region")["total_venta"]
                    .sum()
                    .sort_values(
                        ascending=False
                    )
                )

                display(
                    resultado.to_frame(
                        "Total vendido"
                    )
                )


            elif consulta == "6":

                resultado = (
                    df_agrupada
                    .groupby("metodo_pago")["total_venta"]
                    .sum()
                    .sort_values(
                        ascending=False
                    )
                )

                display(
                    resultado.to_frame(
                        "Total vendido"
                    )
                )


            elif consulta == "7":

                resultado = (
                    df_agrupada
                    .groupby("producto")["cantidad"]
                    .sum()
                    .sort_values(
                        ascending=False
                    )
                )

                display(
                    resultado.to_frame(
                        "Cantidad total vendida"
                    )
                )


            elif consulta == "8":

                resultado = (
                    df_agrupada
                    .groupby("producto")["precio_unitario"]
                    .mean()
                    .sort_values(
                        ascending=False
                    )
                )

                display(
                    resultado.to_frame(
                        "Precio promedio"
                    )
                )


            elif consulta == "9":

                resultado = (
                    df_agrupada
                    .groupby("producto")
                    .size()
                    .sort_values(
                        ascending=False
                    )
                )

                display(
                    resultado.to_frame(
                        "Cantidad de ventas"
                    )
                )


            elif consulta in ["10", "11", "12"]:

                print("""
1. De mayor a menor
2. De menor a mayor
""")


                orden = input(
                    "Seleccione una opción: "
                ).strip()


                if consulta == "10":

                    resultado = (
                        df_agrupada
                        .groupby("producto")["total_venta"]
                        .sum()
                    )

                    nombre = "Total vendido"


                elif consulta == "11":

                    resultado = (
                        df_agrupada
                        .groupby("producto")["precio_unitario"]
                        .mean()
                    )

                    nombre = "Precio promedio"


                else:

                    resultado = (
                        df_agrupada
                        .groupby("producto")["cantidad"]
                        .sum()
                    )

                    nombre = "Cantidad vendida"


                if orden == "1":

                    resultado = resultado.sort_values(
                        ascending=False
                    )

                    display(
                        resultado.to_frame(nombre)
                    )


                elif orden == "2":

                    resultado = resultado.sort_values(
                        ascending=True
                    )

                    display(
                        resultado.to_frame(nombre)
                    )


                else:

                    print(
                        "\nOpción no válida."
                    )


            elif consulta == "0":

                break


            else:

                print(
                    "\nOpción no válida."
                )



    # OPCIÓN 10. REPRESENTACIONES GRÁFICAS


    elif opcion == "10":


        print(
            "============ REPRESENTACIONES GRÁFICAS============"
        )


        if not tabla_limpia():

            print(
                "\nPrimero debes ejecutar las opciones 4, 5 y 6."
            )

            continue


        df_graficos = df_modificada.copy()


        # Calculamos el total de venta.
        df_graficos["total_venta"] = (
            df_graficos["cantidad"]
            *
            df_graficos["precio_unitario"]
        )


        while True:

            print("""
===== MENÚ DE REPRESENTACIONES GRÁFICAS =====

1. Total de ventas por producto
2. Total de ventas por vendedor
3. Cantidad total vendida por producto
4. Precio promedio por producto
5. Total de ventas por categoría
6. Porcentaje de ventas por método de pago
7. Distribución de precios unitarios
8. Cuartiles y valores atípicos del precio
0. Regresar
""")


            grafico = input(
                "Seleccione una opción: "
            ).strip()



            # 1. VENTAS POR PRODUCTO

            if grafico == "1":

                datos = (
                    df_graficos
                    .groupby("producto")["total_venta"]
                    .sum()
                    .sort_values(
                        ascending=False
                    )
                )


                plt.figure(
                    figsize=(12, 6)
                )


                plt.bar(
                    datos.index,
                    datos.values
                )


                plt.title(
                    "Total de ventas por producto"
                )

                plt.xlabel(
                    "Producto"
                )

                plt.ylabel(
                    "Total vendido (₡)"
                )


                plt.xticks(
                    rotation=45,
                    ha="right"
                )


                plt.tight_layout()

                plt.show()



            # 2. VENTAS POR VENDEDOR

            elif grafico == "2":

                datos = (
                    df_graficos
                    .groupby("vendedor")["total_venta"]
                    .sum()
                    .sort_values(
                        ascending=False
                    )
                )


                plt.figure(
                    figsize=(10, 6)
                )


                barras = plt.bar(
                    datos.index,
                    datos.values
                )


                for barra in barras:

                    valor = barra.get_height()

                    plt.text(
                        barra.get_x()
                        +
                        barra.get_width() / 2,
                        valor,
                        f"₡{valor:,.0f}",
                        ha="center",
                        va="bottom"
                    )


                plt.title(
                    "Total de ventas por vendedor"
                )

                plt.xlabel(
                    "Vendedor"
                )

                plt.ylabel(
                    "Total vendido (₡)"
                )


                plt.xticks(
                    rotation=45,
                    ha="right"
                )


                plt.tight_layout()

                plt.show()



            # 3. CANTIDAD VENDIDA POR PRODUCTO

            elif grafico == "3":

                datos = (
                    df_graficos
                    .groupby("producto")["cantidad"]
                    .sum()
                    .sort_values(
                        ascending=False
                    )
                )


                plt.figure(
                    figsize=(12, 6)
                )


                plt.bar(
                    datos.index,
                    datos.values
                )


                plt.title(
                    "Cantidad total vendida por producto"
                )

                plt.xlabel(
                    "Producto"
                )

                plt.ylabel(
                    "Cantidad vendida"
                )


                plt.xticks(
                    rotation=45,
                    ha="right"
                )


                plt.tight_layout()

                plt.show()



            # 4. PRECIO PROMEDIO

            elif grafico == "4":

                datos = (
                    df_graficos
                    .groupby("producto")["precio_unitario"]
                    .mean()
                    .sort_values(
                        ascending=False
                    )
                )


                plt.figure(
                    figsize=(12, 6)
                )


                plt.bar(
                    datos.index,
                    datos.values
                )


                plt.title(
                    "Precio unitario promedio por producto"
                )

                plt.xlabel(
                    "Producto"
                )

                plt.ylabel(
                    "Precio promedio (₡)"
                )


                plt.xticks(
                    rotation=45,
                    ha="right"
                )


                plt.tight_layout()

                plt.show()



            # 5. VENTAS POR CATEGORÍA

            elif grafico == "5":

                datos = (
                    df_graficos
                    .groupby("categoria")["total_venta"]
                    .sum()
                    .sort_values(
                        ascending=False
                    )
                )


                plt.figure(
                    figsize=(10, 6)
                )


                plt.bar(
                    datos.index,
                    datos.values
                )


                plt.title(
                    "Total de ventas por categoría"
                )

                plt.xlabel(
                    "Categoría"
                )

                plt.ylabel(
                    "Total vendido (₡)"
                )


                plt.xticks(
                    rotation=45,
                    ha="right"
                )


                plt.tight_layout()

                plt.show()


            # 6. MÉTODO DE PAGO

            elif grafico == "6":

                datos = (
                    df_graficos
                    .groupby("metodo_pago")["total_venta"]
                    .sum()
                )


                plt.figure(
                    figsize=(8, 8)
                )


                plt.pie(
                    datos.values,
                    labels=datos.index,
                    autopct="%1.1f%%",
                    startangle=90
                )


                plt.title(
                    "Porcentaje de ventas por método de pago"
                )


                plt.show()


            # 7. HISTOGRAMA DE PRECIOS

            elif grafico == "7":

                plt.figure(
                    figsize=(10, 6)
                )


                plt.hist(
                    df_graficos[
                        "precio_unitario"
                    ].dropna(),
                    bins=20
                )


                plt.title(
                    "Distribución de precios unitarios"
                )

                plt.xlabel(
                    "Precio unitario (₡)"
                )

                plt.ylabel(
                    "Frecuencia"
                )


                plt.tight_layout()

                plt.show()


            # 8. BOXPLOT Y VALORES ATÍPICOS

            elif grafico == "8":

                precios = (
                    df_graficos[
                        "precio_unitario"
                    ]
                    .dropna()
                )


                Q1 = precios.quantile(0.25)

                Q2 = precios.quantile(0.50)

                Q3 = precios.quantile(0.75)

                RIC = Q3 - Q1

                limite_inferior = (
                    Q1 - 1.5 * RIC
                )

                limite_superior = (
                    Q3 + 1.5 * RIC
                )


                valores_atipicos = precios[
                    (
                        precios
                        < limite_inferior
                    )
                    |
                    (
                        precios
                        > limite_superior
                    )
                ]


                print(
                    f"\nQ1: ₡{Q1:,.2f}"
                )

                print(
                    f"Mediana: ₡{Q2:,.2f}"
                )

                print(
                    f"Q3: ₡{Q3:,.2f}"
                )

                print(
                    f"RIC: ₡{RIC:,.2f}"
                )

                print(
                    f"Límite inferior: ₡{limite_inferior:,.2f}"
                )

                print(
                    f"Límite superior: ₡{limite_superior:,.2f}"
                )


                print(
                    "\nCantidad de valores atípicos:",
                    len(valores_atipicos)
                )


                filas_atipicas = df_graficos[
                    (
                        df_graficos[
                            "precio_unitario"
                        ]
                        < limite_inferior
                    )
                    |
                    (
                        df_graficos[
                            "precio_unitario"
                        ]
                        > limite_superior
                    )
                ]


                if len(filas_atipicas) > 0:

                    print(
                        "\nREGISTROS ATÍPICOS:"
                    )

                    display(
                        filas_atipicas
                    )

                else:

                    print(
                        "\nNo existen registros atípicos."
                    )


                # Creamos el boxplot.
                plt.figure(
                    figsize=(10, 6)
                )


                plt.boxplot(
                    precios,
                    vert=False
                )


                plt.title(
                    "Distribución de precio unitario "
                    "y valores atípicos"
                )


                plt.xlabel(
                    "Precio unitario (₡)"
                )


                plt.tight_layout()

                plt.show()



            # REGRESAR

            elif grafico == "0":

                break


            else:

                print(
                    "\nOpción no válida."
                )

    # OPCIÓN 11. ANÁLISIS ADICIONAL

    elif opcion == "11":


        print(
            "========== ANÁLISIS ADICIONAL=========="
        )


        if not tabla_limpia():

            print(
                "\nPrimero debes ejecutar las opciones 4, 5 y 6."
            )

            continue


        df_analisis = df_modificada.copy()


        # Calculamos el total de cada venta.
        df_analisis["total_venta"] = (
            df_analisis["cantidad"]
            *
            df_analisis["precio_unitario"]
        )


        while True:

            print("""
===== MENÚ DE ANÁLISIS ADICIONAL =====

1. Analizar ventas por cliente frecuente
2. Analizar ventas por método de pago
3. Analizar ventas por región
4. Analizar comportamiento de ventas por fecha
5. Analizar productos más vendidos
0. Regresar
""")


            analisis = input(
                "Seleccione una opción: "
            ).strip()


            # 1. CLIENTE FRECUENTE

            if analisis == "1":

                print(
                    "\n===== CLIENTES FRECUENTES ====="
                )


                clientes = (
                    df_analisis[
                        "cliente_frecuente"
                    ]
                    .astype(str)
                    .str.strip()
                    .str.lower()
                )


                clientes = clientes.replace({

                    "si": "Sí",
                    "sí": "Sí",
                    "no": "No"

                })


                resultado = (
                    df_analisis
                    .assign(
                        cliente_frecuente=clientes
                    )
                    .groupby(
                        "cliente_frecuente"
                    )["total_venta"]
                    .sum()
                    .sort_values(
                        ascending=False
                    )
                )


                display(
                    resultado.to_frame(
                        "Total vendido"
                    )
                )



            # 2. MÉTODO DE PAGO

            elif analisis == "2":

                print(
                    "\n===== ANÁLISIS POR MÉTODO DE PAGO ====="
                )


                resultado = (
                    df_analisis
                    .groupby("metodo_pago")
                    .agg(
                        cantidad_ventas=(
                            "id_venta",
                            "count"
                        ),
                        total_vendido=(
                            "total_venta",
                            "sum"
                        )
                    )
                    .sort_values(
                        "total_vendido",
                        ascending=False
                    )
                )


                display(
                    resultado
                )



            # 3. REGIÓN

            elif analisis == "3":

                print(
                    "\n===== ANÁLISIS POR REGIÓN ====="
                )


                resultado = (
                    df_analisis
                    .groupby("region")
                    .agg(
                        cantidad_ventas=(
                            "id_venta",
                            "count"
                        ),
                        total_vendido=(
                            "total_venta",
                            "sum"
                        )
                    )
                    .sort_values(
                        "total_vendido",
                        ascending=False
                    )
                )


                display(
                    resultado
                )



            # 4. VENTAS POR FECHA

            elif analisis == "4":

                print(
                    "\n===== ANÁLISIS DE VENTAS POR FECHA ====="
                )


                df_fecha = (
                    df_analisis
                    .copy()
                )


                # Extraemos el año.
                df_fecha["año"] = (
                    df_fecha["fecha"]
                    .dt.year
                )


                # Extraemos el mes.
                df_fecha["mes"] = (
                    df_fecha["fecha"]
                    .dt.month
                )


                resultado = (
                    df_fecha
                    .groupby(
                        ["año", "mes"]
                    )["total_venta"]
                    .sum()
                )


                display(
                    resultado.to_frame(
                        "Total vendido"
                    )
                )



            # 5. PRODUCTOS MÁS VENDIDOS

            elif analisis == "5":

                print(
                    "\n===== PRODUCTOS MÁS VENDIDOS ====="
                )


                resultado = (
                    df_analisis
                    .groupby("producto")
                    .agg(
                        cantidad_total=(
                            "cantidad",
                            "sum"
                        ),
                        total_vendido=(
                            "total_venta",
                            "sum"
                        )
                    )
                    .sort_values(
                        "cantidad_total",
                        ascending=False
                    )
                )


                display(
                    resultado
                )


            # REGRESAR

            elif analisis == "0":

                break


            else:

                print(
                    "\nOpción no válida."
                )



    # OPCIÓN 12. SALIR

    elif opcion == "12":



        print(
            "========SALIENDO DEL PROGRAMA========"
        )


        print(
            "\nGracias por utilizar el programa de EDA."
        )


        break



    # OPCIÓN NO VÁLIDA


    else:

        print(
            "\nOpción no válida."
        )

        print(
            "Seleccione una opción del 1 al 12."
        )

================================================
              MENÚ PRINCIPAL
================================================
1. Cargar archivo CSV
2. Introducir nuevos datos
3. Mostrar información del conjunto de datos
4. Analizar tipos de datos
5. Analizar y tratar valores nulos
6. Analizar y tratar datos duplicados
7. Obtener estadísticas descriptivas
8. Filtrar o consultar datos
9. Realizar agrupaciones y operaciones
10. Generar representaciones gráficas
11. Realizar análisis adicional
12. Salir

Seleccione una opción: 1

================================================
             CARGAR ARCHIVO CSV
================================================

Saving ventas_tienda_tecnologia_ampliado.csv to ventas_tienda_tecnologia_ampliado.csv

Archivo cargado correctamente.

Nombre del archivo:
ventas_tienda_tecnologia_ampliado.csv

Cantidad de filas y columnas:
(1185, 10)

Primeras 10 filas del archivo:

,id_venta,fecha,producto,categoria,cantidad,precio_unitario,vendedor,region,metodo_pago,cliente_frecuente
0,304,2025-08-08,Teclado mecánico,Accesorios,3.0,25310.0,Kevin Solano,Alajuela,Sinpe Móvil,No
1,501,2025-09-16,Monitor 27 pulgadas curvo,Monitores,2.0,273125.0,Ana Rojas,Puntarenas,Transferencia,No
2,956,2025-03-21,Funda protectora celular,Accesorios,4.0,7393.0,Marisol Vargas,Cartago,Sinpe Móvil,No
3,43,2025-06-08,Celular gama alta,Celulares,1.0,419700.0,Ana Rojas,San José,Efectivo,No
4,215,2025-05-04,Celular gama media,Celulares,1.0,229000.0,Marisol Vargas,Cartago,Sinpe Móvil,Sí
5,858,2025-02-10,Monitor 24 pulgadas,Monitores,4.0,153773.0,Marisol Vargas,Limón,Transferencia,No
6,94,01/08/2025,Parlante bluetooth,Audio,1.0,25300.0,Fabiola Araya,Cartago,Transferencia,No
7,539,2025-03-15,Laptop gamer 15 pulgadas,Laptops,4.0,1163726.0,Kevin Solano,Puntarenas,Efectivo,No
8,108,2025-05-31,Teclado mecánico,Accesorios,2.0,34300.0,Ana Rojas,Limón,Tarjeta,No
9,298,2025-08-29,Laptop 14 pulgadas,Laptops,1.0,559766.0,Luis Chinchilla,NaN,Efectivo,Sí

Ahora puedes utilizar la opción 2 para introducir nuevos registros.

================================================
              MENÚ PRINCIPAL
================================================
1. Cargar archivo CSV
2. Introducir nuevos datos
3. Mostrar información del conjunto de datos
4. Analizar tipos de datos
5. Analizar y tratar valores nulos
6. Analizar y tratar datos duplicados
7. Obtener estadísticas descriptivas
8. Filtrar o consultar datos
9. Realizar agrupaciones y operaciones
10. Generar representaciones gráficas
11. Realizar análisis adicional
12. Salir

Seleccione una opción: 4

================================================
          ANÁLISIS DE TIPOS DE DATOS
================================================

TABLA ORIGINAL:

                   Nombre de columna Tipo de dato           Ejemplo
id_venta                    id_venta       object               304
fecha                          fecha       object        2025-08-08
producto                    producto       object  Teclado mecánico
categoria                  categoria       object        Accesorios
cantidad                    cantidad      float64               3.0
precio_unitario      precio_unitario      float64           25310.0
vendedor                    vendedor       object      Kevin Solano
region                        region       object          Alajuela
metodo_pago              metodo_pago       object       Sinpe Móvil
cliente_frecuente  cliente_frecuente       object                No

TABLA MODIFICADA:

                   Nombre de columna    Tipo de dato              Ejemplo
id_venta                    id_venta           Int64                  304
fecha                          fecha  datetime64[ns]  2025-08-08 00:00:00
producto                    producto          object     Teclado mecánico
categoria                  categoria          object           Accesorios
cantidad                    cantidad           Int64                    3
precio_unitario      precio_unitario         float64              25310.0
vendedor                    vendedor          object         Kevin Solano
region                        region          object             Alajuela
metodo_pago              metodo_pago          object          Sinpe Móvil
cliente_frecuente  cliente_frecuente          object                   No

Los tipos de datos fueron preparados correctamente.

================================================
              MENÚ PRINCIPAL
================================================
1. Cargar archivo CSV
2. Introducir nuevos datos
3. Mostrar información del conjunto de datos
4. Analizar tipos de datos
5. Analizar y tratar valores nulos
6. Analizar y tratar datos duplicados
7. Obtener estadísticas descriptivas
8. Filtrar o consultar datos
9. Realizar agrupaciones y operaciones
10. Generar representaciones gráficas
11. Realizar análisis adicional
12. Salir

Seleccione una opción: 5

================================================
        ANALIZAR Y TRATAR VALORES NULOS
================================================

Filas completamente vacías: 1
Las filas completamente vacías fueron eliminadas.

CANTIDAD DE VALORES NULOS POR COLUMNA:
id_venta              0
fecha                46
producto              0
categoria             0
cantidad              0
precio_unitario      62
vendedor              0
region               47
metodo_pago           0
cliente_frecuente     0
dtype: int64

Cantidad de filas que contienen al menos un valor nulo: 148

REGISTROS CON VALORES NULOS:

,id_venta,fecha,producto,categoria,cantidad,precio_unitario,vendedor,region,metodo_pago,cliente_frecuente
6,94,NaT,Parlante bluetooth,Audio,1,25300.0,Fabiola Araya,Cartago,Transferencia,No
9,298,2025-08-29,Laptop 14 pulgadas,Laptops,1,559766.0,Luis Chinchilla,NaN,Efectivo,Sí
10,962,NaT,Laptop gamer 15 pulgadas,Laptops,4,948057.0,Fabiola Araya,Heredia,Efectivo,Sí
25,32,NaT,Funda protectora celular,Accesorios,2,NaN,Fabiola Araya,Puntarenas,Efectivo,No
29,426,2025-05-02,Monitor 24 pulgadas,Monitores,3,NaN,Ana Rojas,Guanacaste,Sinpe Móvil,Sí
...,...,...,...,...,...,...,...,...,...,...
1151,134,2025-06-22,Cargador portátil (power bank),Accesorios,4,NaN,Fabiola Araya,Heredia,Efectivo,Sí
1153,485,NaT,Laptop 14 pulgadas,Laptops,2,392184.0,Marisol Vargas,Puntarenas,Efectivo,Sí
1156,428,2025-08-08,Monitor 24 pulgadas,Monitores,1,153037.0,Ana Rojas,NaN,Sinpe Móvil,Si
1159,430,2025-01-23,Funda protectora celular,Accesorios,4,7811.0,Kevin Solano,NaN,Tarjeta,No
1161,827,NaT,Laptop gamer 15 pulgadas,Laptops,2,1173030.0,Ana Rojas,Guanacaste,Efectivo,Sí

REGISTROS CON FECHA NULA:
Cantidad: 46

,id_venta,fecha,producto,categoria,cantidad,precio_unitario,vendedor,region,metodo_pago,cliente_frecuente
6,94,NaT,Parlante bluetooth,Audio,1,25300.0,Fabiola Araya,Cartago,Transferencia,No
10,962,NaT,Laptop gamer 15 pulgadas,Laptops,4,948057.0,Fabiola Araya,Heredia,Efectivo,Sí
25,32,NaT,Funda protectora celular,Accesorios,2,NaN,Fabiola Araya,Puntarenas,Efectivo,No
34,703,NaT,Audífonos inalámbricos,Audio,2,33695.0,Fabiola Araya,Cartago,Efectivo,No
66,416,NaT,Cargador portátil (power bank),Accesorios,3,17116.0,ana rojas,Guanacaste,Transferencia,no
133,945,NaT,Funda protectora celular,Accesorios,1,3638.0,Kevin Solano,Cartago,Transferencia,No
169,232,NaT,Laptop gamer 15 pulgadas,Laptops,3,894594.0,luis chinchilla,Puntarenas,Transferencia,Sí
220,1046,NaT,Monitor 27 pulgadas curvo,Monitores,2,293978.0,Fabiola Araya,Heredia,Tarjeta,Sí
231,291,NaT,Laptop 14 pulgadas,Laptops,4,459412.0,Fabiola Araya,Guanacaste,Tarjeta,Sí
241,106,NaT,Laptop 14 pulgadas,Laptops,1,553700.0,Ana Rojas,San José,Sinpe Móvil,No
256,459,NaT,Parlante bluetooth,Audio,2,36507.0,Fabiola Araya,Guanacaste,Efectivo,No
305,792,NaT,Monitor 27 pulgadas curvo,Monitores,4,233229.0,Luis Chinchilla,Heredia,Transferencia,Sí
311,188,NaT,Mouse inalámbrico,Accesorios,1,12000.0,Luis Chinchilla,Alajuela,Sinpe Móvil,Sí
332,34,NaT,Celular gama media,Celulares,4,153700.0,Marisol Vargas,Limón,Sinpe Móvil,No
333,89,NaT,Teclado mecánico,accesorios,1,35200.0,Kevin Solano,Cartago,Tarjeta,No
354,1021,NaT,Celular gama media,celulares,3,170467.0,Kevin Solano,Guanacaste,Tarjeta,No
356,477,NaT,Teclado mecánico,Accesorios,2,31846.0,ana rojas,Guanacaste,Sinpe Móvil,Sí
378,724,NaT,Teclado mecánico,Accesorios,2,NaN,Fabiola Araya,Guanacaste,Transferencia,No
438,99,NaT,Monitor 24 pulgadas,Monitores,1,176500.0,Fabiola Araya,Heredia,Efectivo,No
460,596,NaT,Cargador portátil (power bank),Accesorios,1,20858.0,Fabiola Araya,San José,Efectivo,No
463,836,NaT,Mouse inalámbrico,Accesorios,4,7687.0,Ana Rojas,Desconocida,Efectivo,Sí
495,385,NaT,Mouse inalámbrico,Accesorios,5,12632.0,Kevin Solano,Alajuela,Efectivo,No
503,830,NaT,Funda protectora celular,Accesorios,5,4682.0,Marisol Vargas,Limón,Transferencia,No
507,916,NaT,Mouse inalámbrico,Accesorios,5,12764.0,Ana Rojas,Puntarenas,Transferencia,No
508,330,NaT,Celular gama alta,Celulares,2,520265.0,Fabiola Araya,Cartago,Efectivo,No
510,528,NaT,Audífonos inalámbricos,Audio,2,18359.0,Marisol Vargas,Guanacaste,Efectivo,Sí
519,138,NaT,Audífonos inalámbricos,Audio,3,23200.0,Fabiola Araya,Desconocida,Sinpe Móvil,Sí
521,644,NaT,Monitor 24 pulgadas,Monitores,2,150298.0,Fabiola Araya,Cartago,Efectivo,Sí
522,751,NaT,Laptop gamer 15 pulgadas,Laptops,3,1043397.0,Luis Chinchilla,Guanacaste,Sinpe Móvil,No
568,680,NaT,Monitor 24 pulgadas,Monitores,1,178075.0,Ana Rojas,Puntarenas,Transferencia,No
589,977,NaT,Teclado mecánico,Accesorios,3,34122.0,Fabiola Araya,Heredia,Sinpe Móvil,Sí
621,823,NaT,Celular gama alta,Celulares,2,614966.0,Fabiola Araya,San José,Sinpe Móvil,si
626,38,NaT,Monitor 24 pulgadas,Monitores,1,NaN,Luis Chinchilla,Cartago,Tarjeta,No
753,265,NaT,Cargador portátil (power bank),Accesorios,4,18952.0,Luis Chinchilla,Alajuela,Transferencia,Sí
843,197,NaT,Monitor 24 pulgadas,Monitores,1,177500.0,Fabiola Araya,Alajuela,Transferencia,sí
844,80,NaT,Celular gama alta,Celulares,2,484300.0,Fabiola Araya,Puntarenas,Efectivo,No
890,375,NaT,Parlante bluetooth,Audio,3,37115.0,Luis Chinchilla,Alajuela,Sinpe Móvil,No
907,213,NaT,Funda protectora celular,Accesorios,1,NaN,Marisol Vargas,San José,Sinpe Móvil,No
966,1145,NaT,Celular gama media,Celulares,5,248093.0,Luis Chinchilla,Heredia,Efectivo,No
979,869,NaT,Laptop gamer 15 pulgadas,Laptops,3,697685.0,Kevin Solano,Heredia,Tarjeta,No
1032,1,NaT,Cargador portátil (power bank),Accesorios,1,12600.0,Luis Chinchilla,Alajuela,Tarjeta,No
1053,301,NaT,Teclado mecánico,Accesorios,5,35538.0,Luis Chinchilla,Limón,Efectivo,no
1058,448,NaT,Parlante bluetooth,Audio,5,39892.0,Kevin Solano,Limón,Efectivo,Sí
1079,16,NaT,Teclado mecánico,Accesorios,5,43100.0,Luis Chinchilla,Guanacaste,Transferencia,No
1153,485,NaT,Laptop 14 pulgadas,Laptops,2,392184.0,Marisol Vargas,Puntarenas,Efectivo,Sí
1161,827,NaT,Laptop gamer 15 pulgadas,Laptops,2,1173030.0,Ana Rojas,Guanacaste,Efectivo,Sí

REGISTROS CON PRECIO_UNITARIO NULO:
Cantidad: 62

,id_venta,fecha,producto,categoria,cantidad,precio_unitario,vendedor,region,metodo_pago,cliente_frecuente
25,32,NaT,Funda protectora celular,Accesorios,2,NaN,Fabiola Araya,Puntarenas,Efectivo,No
29,426,2025-05-02,Monitor 24 pulgadas,Monitores,3,NaN,Ana Rojas,Guanacaste,Sinpe Móvil,Sí
30,81,2025-05-17,Mouse inalámbrico,Accesorios,3,NaN,Marisol Vargas,Limón,Sinpe Móvil,No
37,163,2025-05-16,Teclado mecánico,Accesorios,2,NaN,Kevin Solano,Puntarenas,Tarjeta,No
68,866,2025-05-07,Funda protectora celular,Accesorios,1,NaN,Luis Chinchilla,Heredia,Efectivo,No
...,...,...,...,...,...,...,...,...,...,...
1113,310,2025-04-08,Monitor 27 pulgadas curvo,Monitores,1,NaN,Fabiola Araya,Guanacaste,Efectivo,No
1122,432,2025-06-30,Cargador portátil (power bank),Accesorios,5,NaN,Ana Rojas,Limón,Sinpe Móvil,No
1130,980,2025-02-09,Celular gama media,Celulares,5,NaN,Luis Chinchilla,Heredia,Sinpe Móvil,No
1144,1103,2025-02-09,Funda protectora celular,Accesorios,1,NaN,Luis Chinchilla,Guanacaste,Transferencia,No
1151,134,2025-06-22,Cargador portátil (power bank),Accesorios,4,NaN,Fabiola Araya,Heredia,Efectivo,Sí

MEDIANA DEL PRECIO UNITARIO POR PRODUCTO:

producto
Audifonos inalambricos             22079.0
Audífonos inalámbricos             26913.0
Cargador portatil (power bank)     13053.0
Cargador portátil (power bank)     14579.0
Celular gama alta                 520265.0
Celular gama media                211019.0
Funda protectora celular            5564.0
Laptop 14 pulgadas                488664.0
Laptop gamer 15 pulgadas          979278.0
Monitor 24 pulgadas               147268.0
Monitor 27 pulgadas curvo         278803.0
Mouse inalámbrico                   9979.5
Parlante bluetooth                 36959.5
Teclado mecánico                   34167.0
Name: precio_unitario, dtype: float64

REGISTROS CON CANTIDAD NULA:
Cantidad: 0

REGISTROS CON ID_VENTA NULO:
Cantidad: 0

================================================
       NULOS DESPUÉS DEL TRATAMIENTO
================================================
id_venta              0
fecha                46
producto              0
categoria             0
cantidad              0
precio_unitario       0
vendedor              0
region                0
metodo_pago           0
cliente_frecuente     0
dtype: int64

CANTIDAD DE 'DESCONOCIDO' POR COLUMNA:
categoria      0
producto       0
vendedor       0
metodo_pago    0
dtype: int64

Tratamiento de valores nulos terminado.

================================================
              MENÚ PRINCIPAL
================================================
1. Cargar archivo CSV
2. Introducir nuevos datos
3. Mostrar información del conjunto de datos
4. Analizar tipos de datos
5. Analizar y tratar valores nulos
6. Analizar y tratar datos duplicados
7. Obtener estadísticas descriptivas
8. Filtrar o consultar datos
9. Realizar agrupaciones y operaciones
10. Generar representaciones gráficas
11. Realizar análisis adicional
12. Salir

Seleccione una opción: 12

==============================================
          SALIENDO DEL PROGRAMA
==============================================

Gracias por utilizar el programa de EDA.